using Microsoft.ML.OnnxRuntime;
using T3.Core.Logging;

namespace t3.streamdiffusion.Onnx;

/// <summary>
/// A latent tensor living in GPU memory. Produced either by a device-bound
/// session output (owns the output collection it came from) or wrapped around
/// CPU data ORT will copy on the next bound run. Every GpuTensor must be
/// disposed exactly once; ops take no ownership of their inputs.
/// </summary>
public sealed class GpuTensor : IDisposable
{
    private readonly IDisposableReadOnlyCollection<OrtValue>? _owner;

    public OrtValue Value { get; }

    private GpuTensor(OrtValue value, IDisposableReadOnlyCollection<OrtValue>? owner)
    {
        Value = value;
        _owner = owner;
    }

    /// <summary>Wraps CPU data for a single bound run (no copy until the run).</summary>
    public static GpuTensor Cpu(float[] data, long[] shape)
    {
        return new GpuTensor(OrtValue.CreateTensorValueFromMemory(data, shape), null);
    }

    internal static GpuTensor FromBoundOutput(IDisposableReadOnlyCollection<OrtValue> outputs)
    {
        if (outputs.Count != 1)
            throw new InvalidOperationException($"Expected one bound output, got {outputs.Count}");
        return new GpuTensor(outputs[0], outputs);
    }

    public void Dispose()
    {
        if (_owner != null)
        {
            _owner.Dispose(); // disposes the contained OrtValue(s) too
        }
        else
        {
            Value.Dispose();
        }
    }
}

/// <summary>
/// GPU-resident latent math for the realtime flow: the tiny lat_scale
/// (out = a·k) and lat_combine (out = a·k1 + b·k2 + c·k3) graphs generated by
/// tools/make-latent-ops.py, run with IO binding and device-bound outputs so
/// latents never round-trip through CPU memory between VAE encode, the UNet
/// denoise loop and VAE decode. All scheduler formulas reduce to these two
/// shapes with per-step scalars computed on the CPU from the same tables.
/// </summary>
public sealed class GpuLatentOps : IDisposable
{
    private readonly OnnxModelSession _scale;
    private readonly OnnxModelSession _combine;
    private readonly OrtIoBinding _scaleBinding;
    private readonly OrtIoBinding _combineBinding;
    private readonly OrtMemoryInfo _deviceMemory;
    private readonly long[] _scalarShape = { 1 };

    private GpuLatentOps(OnnxModelSession scale, OnnxModelSession combine, int deviceId)
    {
        _scale = scale;
        _combine = combine;
        // Must match the allocator the CUDA EP registers (an arena) - a raw
        // DeviceAllocator request here forces cudaMalloc/cudaFree per run.
        _deviceMemory = new OrtMemoryInfo("Cuda", OrtAllocatorType.ArenaAllocator, deviceId, OrtMemType.Default);
        _scaleBinding = _scale.CreateIoBinder();
        _combineBinding = _combine.CreateIoBinder();
    }

    /// <summary>Non-null when the model directory provides the latent-op graphs and CUDA is available.</summary>
    public static GpuLatentOps? TryCreate(string modelDirectory, int deviceId)
    {
        var scalePath = Path.Combine(modelDirectory, "lat_scale.onnx");
        var combinePath = Path.Combine(modelDirectory, "lat_combine.onnx");
        if (!File.Exists(scalePath) || !File.Exists(combinePath))
            return null;

        // The graphs run on CUDA even when the pipeline uses TensorRT - they are
        // 3-5 node Mul/Add graphs; a TRT engine build for them would be absurd.
        var scale = OnnxModelSession.Create(scalePath, deviceId, "LatScale", ExecutionProvider.Cuda);
        if (scale == null)
            return null;

        var combine = OnnxModelSession.Create(combinePath, deviceId, "LatCombine", ExecutionProvider.Cuda);
        if (combine == null)
        {
            scale.Dispose();
            return null;
        }

        try
        {
            return new GpuLatentOps(scale, combine, deviceId);
        }
        catch (Exception ex)
        {
            Log.Warning($"[StreamDiffusion] GPU latent flow unavailable: {ex.Message}");
            scale.Dispose();
            combine.Dispose();
            return null;
        }
    }

    public OrtMemoryInfo DeviceMemory => _deviceMemory;

    /// <summary>out = a · k. Caller disposes <paramref name="a"/>.</summary>
    public GpuTensor Scale(GpuTensor a, float k)
    {
        var binding = _scaleBinding;
        using var kv = OrtValue.CreateTensorValueFromMemory(new[] { k }, _scalarShape);
        binding.ClearBoundInputs();
        binding.ClearBoundOutputs();
        binding.BindInput("a", a.Value);
        binding.BindInput("k", kv);
        binding.BindOutputToDevice("out", _deviceMemory);
        _scale.RunBound(binding);
        // Ownership of the collection (and the OrtValue in it) moves into the
        // GpuTensor - do NOT dispose it here, the chained consumer needs it.
        return GpuTensor.FromBoundOutput(binding.GetOutputValues());
    }

    /// <summary>out = a·k1 + b·k2 + c·k3. Caller disposes the inputs. c may be null (k3 should be 0).</summary>
    public GpuTensor Combine(GpuTensor a, GpuTensor b, GpuTensor? c, float k1, float k2, float k3)
    {
        var binding = _combineBinding;
        using var k1v = OrtValue.CreateTensorValueFromMemory(new[] { k1 }, _scalarShape);
        using var k2v = OrtValue.CreateTensorValueFromMemory(new[] { k2 }, _scalarShape);
        using var k3v = OrtValue.CreateTensorValueFromMemory(new[] { k3 }, _scalarShape);
        binding.ClearBoundInputs();
        binding.ClearBoundOutputs();
        binding.BindInput("a", a.Value);
        binding.BindInput("b", b.Value);
        binding.BindInput("c", (c ?? a).Value);
        binding.BindInput("k1", k1v);
        binding.BindInput("k2", k2v);
        binding.BindInput("k3", k3v);
        binding.BindOutputToDevice("out", _deviceMemory);
        _combine.RunBound(binding);
        return GpuTensor.FromBoundOutput(binding.GetOutputValues());
    }

    public void Dispose()
    {
        _scaleBinding.Dispose();
        _combineBinding.Dispose();
        _scale.Dispose();
        _combine.Dispose();
    }
}
